"""Display SQL queries generated by Django ORM."""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from employees.models import Employee
from attendance.models import AttendanceRecord
from performance.models import PerformanceReview
from django.db.models import Count, Avg, Q


def print_query(queryset, description):
    """Print the SQL query Django will execute."""
    print(f"\n{'='*80}")
    print(f"{description}")
    print(f"{'='*80}")
    print(str(queryset.query))


print("="*80)
print("DJANGO ORM → SQL QUERY EXAMPLES")
print("="*80)

# Simple SELECT
print_query(
    Employee.objects.filter(department="Engineering"),
    "1. SELECT with WHERE"
)

# JOIN
print_query(
    AttendanceRecord.objects.select_related('employee').filter(status='present'),
    "2. SELECT with INNER JOIN"
)

# GROUP BY
print_query(
    Employee.objects.values('department').annotate(count=Count('id')),
    "3. SELECT with GROUP BY"
)

# AVG with JOIN
print_query(
    PerformanceReview.objects.values(
        'employee__first_name',
        'employee__last_name'
    ).annotate(avg_rating=Avg('rating')).order_by('-avg_rating'),
    "4. SELECT with JOIN, GROUP BY, AVG, ORDER BY"
)

# Complex WHERE
print_query(
    Employee.objects.filter(
        Q(department='Engineering') | Q(department='Analytics'),
        status=Employee.EmploymentStatus.ACTIVE,
        date_hired__gte='2019-01-01'
    ),
    "5. SELECT with complex WHERE (OR and AND)"
)

print("\n" + "="*80)
print("Django ORM translates Python code to SQL automatically!")
print("="*80)
