# Generated by Django 5.2.8 on 2025-11-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('reviewer_name', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('overall_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-review_period_end', 'employee__last_name'],
                'indexes': [models.Index(fields=['employee', 'review_period_end'], name='performance_employe_97f255_idx'), models.Index(fields=['review_period_start', 'review_period_end'], name='performance_review__17f819_idx')],
            },
        ),
    ]
