"""
Project level URL configuration.

URLs are like a map of your website - they tell Django which view
to run when someone visits a particular URL.

Think of it like: URL pattern → View function → Template/Response
"""
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

# Import API viewsets (these handle the REST API endpoints)
from employees.api import EmployeeViewSet
from employees.views import employee_login, employee_logout, employee_dashboard, mark_attendance
from attendance.api import AttendanceRecordViewSet
from performance.api import PerformanceReviewViewSet

# Router automatically creates URLs for our API viewsets
# It creates URLs like /employees/, /employees/1/, etc.
router = routers.DefaultRouter()
router.register(r"employees", EmployeeViewSet, basename="employee")
router.register(r"attendance", AttendanceRecordViewSet, basename="attendance")
router.register(r"performance", PerformanceReviewViewSet, basename="performance")

# URL patterns - order matters! Django checks from top to bottom
urlpatterns = [
    # Employee Portal (Main Page) - these come first!
    path("", employee_login, name="employee_login"),  # Root URL (/) shows login
    path("dashboard/", employee_dashboard, name="employee_dashboard"),  # After login
    path("logout/", employee_logout, name="employee_logout"),  # Logout
    path("mark-attendance/", mark_attendance, name="mark_attendance"),  # Form submission
    
    # Admin and API - these are for admins/developers
    path("admin/", admin.site.urls),  # Django admin panel
    path("api/", include(router.urls)),  # REST API endpoints (auto-generated by router)
    path("api/reports/", include("reports.urls")),  # Custom reports URLs
]
